/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package twitleme;
import java.awt.Color;
import java.util.regex.Pattern;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Y
 */
public class cikcikleme_sayfasi extends javax.swing.JFrame {
    
    String id_no;
    

    /** Creates new form cikcikleme_sayfasi */
    public cikcikleme_sayfasi() {
        initComponents();
    }
  
    public cikcikleme_sayfasi(String id_no)
    {
        this();
        this.id_no=id_no;
    }
     public static void bilgi_kayit2(String veri)
    {
        File file=new File("C:\\cikcik1\\cikcikler.txt");
        try
        {
            FileOutputStream dosya= new FileOutputStream(file,true);
            dosya.write(veri.getBytes());
            dosya.flush();
            dosya.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
      public static String gerceklestir()
    {
        String deger3="";
        File file=new File("C:\\cikcik1\\cikcikler.txt");
        try
        {
            Scanner giris=new Scanner(file);
           
                  deger3=giris.nextLine();
                  
                          giris.close();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
       return deger3; 
    }
   
   

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gun = new javax.swing.JComboBox<>();
        ay = new javax.swing.JComboBox<>();
        yil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        konu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cikcikleme_bosluk = new javax.swing.JTextArea();
        giris_Yap = new javax.swing.JButton();
        aa = new javax.swing.JTextField();
        bb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gun.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        gun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "14", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        gun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gunItemStateChanged(evt);
            }
        });
        gun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunActionPerformed(evt);
            }
        });

        ay.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        ay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yil.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        yil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        yil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yilActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 17)); // NOI18N
        jLabel5.setText(" konu");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setText("  cikcikleme");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 17)); // NOI18N
        jLabel6.setText(" Tarih");

        konu.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        konu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konuActionPerformed(evt);
            }
        });

        cikcikleme_bosluk.setColumns(20);
        cikcikleme_bosluk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cikcikleme_bosluk.setRows(5);
        jScrollPane1.setViewportView(cikcikleme_bosluk);

        giris_Yap.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        giris_Yap.setText("cikcikle");
        giris_Yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_YapActionPerformed(evt);
            }
        });

        aa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(konu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(gun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(yil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(giris_Yap))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giris_Yap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gunActionPerformed

    private void yilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yilActionPerformed

    private void konuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konuActionPerformed

    private void giris_YapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_YapActionPerformed
         boolean b=Pattern.matches("\\w{0,140}", cikcikleme_bosluk.getText());
         boolean kontrol6=true;
       if(b)
       {
        bb.setForeground(new Color(0,150,0));
        bb.setText("DOGRU");
        
       }
       else
       {
           bb.setForeground(new Color(150,0,0));
           bb.setText("YANLIS");
        kontrol6=false;
       }   
       /* if(cikcikleme_bosluk.getText().length()>
                140)
        {
            JOptionPane.showMessageDialog(rootPane,"cikcikleme metini en fazla 140 karakterden olusur");
        }
        if(konu.getText().length()==0)
        {
            JOptionPane.showMessageDialog(rootPane,"cikcikleme konusu giriniz");
        }
       */
        int sayac=0;
        String ayi="";
        String gunu="";
        int gin_ind=gun.getSelectedIndex();
        if(gin_ind<9)
        {
            gunu="0"+(gin_ind+1);
        }
        else
        {
            gunu=""+(gin_ind+1);
        }
        int ay_ind=ay.getSelectedIndex();
         if(ay_ind<9)
        {
            ayi="0"+(ay_ind+1);
        }
        else
        {
             ayi=""+(ay_ind+1);
        }
               String karakter=";";
               String karakter2=")";
        String user3[]=gerceklestir().split(karakter);
        for(int i=1;i<user3.length-1;i=i+5)
        {
            
            if(user3[i].equals(cikcikleme_bosluk.getText()))
            {              
                sayac=Integer.parseInt(user3[i+3]);
                sayac++;       
            }
        }
        
        String tarih=gunu+"."+ayi+"."+(yil.getSelectedIndex()+1900);
        if(kontrol6){
        String cikcikleme=id_no+";"+cikcikleme_bosluk.getText()+";"+"#"+konu.getText()+";"+tarih+";"+sayac+"; ";
        String cikcikleme2="("+id_no+";"+cikcikleme_bosluk.getText()+";"+"#"+konu.getText()+";"+tarih+";"+sayac+")";

        bilgi_kayit2(cikcikleme);
        aa.setText(cikcikleme2);
        }
    }//GEN-LAST:event_giris_YapActionPerformed

    private void gunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gunItemStateChanged
        
    }//GEN-LAST:event_gunItemStateChanged

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
          

    }//GEN-LAST:event_aaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cikcikleme_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cikcikleme_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cikcikleme_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cikcikleme_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cikcikleme_sayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField aa;
    private javax.swing.JComboBox<String> ay;
    private javax.swing.JLabel bb;
    public javax.swing.JTextArea cikcikleme_bosluk;
    public javax.swing.JButton giris_Yap;
    private javax.swing.JComboBox<String> gun;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField konu;
    private javax.swing.JComboBox<String> yil;
    // End of variables declaration//GEN-END:variables

}
